// Carrier contact list — fill in emails as you find them
// status: "email" | "form" | "phone" | "tbd"
// contact: email address if status === "email", otherwise URL or phone

export const carriers = [
  // ─── PLACEHOLDER — will be filled after research agent completes ───
  // Format:
  // { name: "Allstate", contact: "appointments@allstate.com", status: "email", notes: "" },
  // { name: "Progressive", contact: "https://agents.progressive.com/appoint", status: "form", notes: "Use online portal" },

  // MAJOR NATIONAL
  { name: "Allstate",           contact: "appointments@allstate.com",             status: "tbd", notes: "" },
  { name: "Nationwide",         contact: "agencyappointments@nationwide.com",      status: "tbd", notes: "" },
  { name: "Liberty Mutual",     contact: "agentappointments@libertymutual.com",    status: "tbd", notes: "" },
  { name: "Travelers",          contact: "agencyappointments@travelers.com",       status: "tbd", notes: "" },
  { name: "Progressive",        contact: "newagency@progressive.com",              status: "tbd", notes: "" },
  { name: "The Hartford",       contact: "agentappointments@thehartford.com",      status: "tbd", notes: "" },
  { name: "Geico",              contact: "",                                        status: "form", notes: "GEICO does not appoint independent agents" },

  // PERSONAL LINES
  { name: "Safeco",             contact: "agentappointments@safeco.com",           status: "tbd", notes: "" },
  { name: "Encompass",          contact: "encompassagents@allstate.com",           status: "tbd", notes: "" },
  { name: "National General",   contact: "appointments@nationalgeneral.com",       status: "tbd", notes: "" },
  { name: "Mercury",            contact: "agentappointments@mercuryinsurance.com", status: "tbd", notes: "" },
  { name: "Foremost",           contact: "agentappointments@foremost.com",         status: "tbd", notes: "" },
  { name: "Bristol West",       contact: "agentservices@bristolwest.com",          status: "tbd", notes: "" },
  { name: "Dairyland",          contact: "appointments@dairyland.com",             status: "tbd", notes: "" },
  { name: "Elephant",           contact: "agentappointments@elephant.com",         status: "tbd", notes: "" },
  { name: "The General",        contact: "agentappointments@thegeneral.com",       status: "tbd", notes: "" },
  { name: "Trexis",             contact: "appointments@trexisinsurance.com",       status: "tbd", notes: "" },
  { name: "GAINSCO",            contact: "agentappointments@gainsco.com",          status: "tbd", notes: "" },
  { name: "Kemper Auto",        contact: "agentappointments@kemper.com",           status: "tbd", notes: "" },
  { name: "Clearcover",         contact: "partners@clearcover.com",                status: "tbd", notes: "" },
  { name: "Lemonade",           contact: "agents@lemonade.com",                    status: "tbd", notes: "" },
  { name: "Hugo",               contact: "partners@joinhugo.com",                  status: "tbd", notes: "" },
  { name: "Branch",             contact: "agents@ourbranch.com",                   status: "tbd", notes: "" },
  { name: "Bamboo",             contact: "appointments@bambooinsurance.com",       status: "tbd", notes: "" },
  { name: "Obie",               contact: "partners@obieinsurance.com",             status: "tbd", notes: "" },
  { name: "Openly",             contact: "appointments@openly.com",                status: "tbd", notes: "" },
  { name: "Steadily",           contact: "agents@steadily.com",                    status: "tbd", notes: "" },
  { name: "Cover Tree",         contact: "agents@covertree.com",                   status: "tbd", notes: "" },
  { name: "Cover Whale",        contact: "appointments@coverwhale.com",            status: "tbd", notes: "" },
  { name: "Swyfft",             contact: "agents@swyfft.com",                      status: "tbd", notes: "" },
  { name: "Orion180",           contact: "agents@orion180.com",                    status: "tbd", notes: "" },
  { name: "Homeowners of America", contact: "agents@homeownersofamerica.com",     status: "tbd", notes: "" },
  { name: "Heritage",           contact: "appointments@heritagepci.com",           status: "tbd", notes: "" },
  { name: "Universal Property", contact: "agentappointments@upcic.com",            status: "tbd", notes: "" },
  { name: "Tower Hill",         contact: "agentappointments@towerhill.com",        status: "tbd", notes: "" },
  { name: "Cabrillo Coastal",   contact: "appointments@cabrillocoastal.com",       status: "tbd", notes: "" },
  { name: "Gulfstream",         contact: "appointments@gulfstreamins.com",         status: "tbd", notes: "" },
  { name: "Cypress",            contact: "agents@cypressig.com",                   status: "tbd", notes: "" },
  { name: "Hagerty",            contact: "agentappointments@hagerty.com",          status: "tbd", notes: "" },
  { name: "SageSure",           contact: "agentpartners@sagesure.com",             status: "tbd", notes: "" },
  { name: "Donegal",            contact: "agentappointments@donegalgroup.com",     status: "tbd", notes: "" },
  { name: "MMG Insurance",      contact: "agentappointments@mmgins.com",           status: "tbd", notes: "" },
  { name: "Mapfre",             contact: "agentappointments@mapfreinsurance.com",  status: "tbd", notes: "" },
  { name: "Grange",             contact: "agentappointments@grangeinsurance.com",  status: "tbd", notes: "" },
  { name: "Secura",             contact: "agentappointments@secura.com",           status: "tbd", notes: "" },
  { name: "American Modern",    contact: "appointments@amig.com",                  status: "tbd", notes: "" },
  { name: "American Strategic", contact: "agents@americanstrategic.com",           status: "tbd", notes: "" },
  { name: "Main Street America",contact: "agentappointments@msagroup.com",         status: "tbd", notes: "" },
  { name: "Hanover",            contact: "agentappointments@hanover.com",          status: "tbd", notes: "" },
  { name: "Lincoln Financial",  contact: "agentappointments@lfg.com",              status: "tbd", notes: "" },
  { name: "Kansas City Life",   contact: "agentappointments@kclife.com",           status: "tbd", notes: "" },
  { name: "Quick Life",         contact: "agents@quicklife.com",                   status: "tbd", notes: "" },
  { name: "Mexico Insurance Online", contact: "agents@mexicoinsurance.com",        status: "tbd", notes: "" },

  // COMMERCIAL / SPECIALTY
  { name: "Chubb",              contact: "agentappointments@chubb.com",            status: "tbd", notes: "" },
  { name: "CNA",                contact: "agentappointments@cna.com",              status: "tbd", notes: "" },
  { name: "Guard Insurance",    contact: "appointments@guard.com",                 status: "tbd", notes: "" },
  { name: "State Auto",         contact: "agentappointments@stateauto.com",        status: "tbd", notes: "" },
  { name: "AmTrust",            contact: "appointments@amtrustfinancial.com",      status: "tbd", notes: "" },
  { name: "Hiscox",             contact: "agentappointments@hiscox.com",           status: "tbd", notes: "" },
  { name: "Guide One",          contact: "agentappointments@guideone.com",         status: "tbd", notes: "" },
  { name: "Cowbell Cyber",      contact: "partners@cowbell.insure",                status: "tbd", notes: "" },
  { name: "Philadelphia",       contact: "appointments@phly.com",                  status: "tbd", notes: "" },
  { name: "Tokio Marine HCC",   contact: "appointments@tmhcc.com",                 status: "tbd", notes: "" },
  { name: "Attune",             contact: "appointments@attuneinsurance.com",       status: "tbd", notes: "" },
  { name: "Indigo",             contact: "appointments@indigoinsurance.com",       status: "tbd", notes: "" },
  { name: "Embark",             contact: "agents@embarkgeneral.com",               status: "tbd", notes: "" },
  { name: "Lemonade",           contact: "agents@lemonade.com",                    status: "tbd", notes: "" },

  // E&S / WHOLESALE / BROKERAGE
  { name: "Burns and Wilcox",   contact: "appointments@burnsandwilcox.com",        status: "tbd", notes: "" },
  { name: "CRC Group",          contact: "appointments@crcgroup.com",              status: "tbd", notes: "" },
  { name: "CRC Tapco",          contact: "appointments@tapco.com",                 status: "tbd", notes: "" },
  { name: "RPS",                contact: "appointments@rpsins.com",                status: "tbd", notes: "" },
  { name: "BTIS",               contact: "appointments@btisinc.com",               status: "tbd", notes: "" },
  { name: "Crump",              contact: "appointments@crumpinsurance.com",        status: "tbd", notes: "" },
  { name: "Arrowhead",          contact: "appointments@arrowheadgrp.com",          status: "tbd", notes: "" },
  { name: "Atlas General",      contact: "appointments@atlasgeneralins.com",       status: "tbd", notes: "" },
  { name: "Aegis General",      contact: "appointments@aegisgeneral.com",          status: "tbd", notes: "" },
  { name: "Allied Trust",       contact: "appointments@alliedtrustic.com",         status: "tbd", notes: "" },
  { name: "Annex Risk",         contact: "appointments@annexrisk.com",             status: "tbd", notes: "" },
  { name: "ICAT",               contact: "appointments@icatinsurance.com",         status: "tbd", notes: "" },
  { name: "Palomar Specialty",  contact: "appointments@palomarspecialty.com",      status: "tbd", notes: "" },
  { name: "Orchid",             contact: "appointments@orchidinsurance.com",       status: "tbd", notes: "" },
  { name: "Wright Flood",       contact: "appointments@wrightflood.com",           status: "tbd", notes: "" },
  { name: "Foremost Signature", contact: "agents@foremostsignature.com",           status: "tbd", notes: "" },
  { name: "Pathpoint",          contact: "agents@pathpoint.com",                   status: "tbd", notes: "" },
  { name: "K2 Specialty",       contact: "appointments@k2specialty.com",           status: "tbd", notes: "" },
  { name: "SES",                contact: "appointments@ses-insurance.com",         status: "tbd", notes: "" },
  { name: "ISC",                contact: "appointments@iscmga.com",                status: "tbd", notes: "" },
  { name: "GBLI",               contact: "appointments@gbli.com",                  status: "tbd", notes: "" },
  { name: "Risico",             contact: "appointments@risico.com",                status: "tbd", notes: "" },
  { name: "ePremium",           contact: "appointments@epremium.com",              status: "tbd", notes: "" },
  { name: "Back Nine",          contact: "appointments@backnineinsurance.com",     status: "tbd", notes: "" },
  { name: "Sport Underwriters", contact: "appointments@sportsunderwriters.com",    status: "tbd", notes: "" },
  { name: "Starwind WC",        contact: "appointments@starwindspecialty.com",     status: "tbd", notes: "" },
  { name: "Victor Insurance",   contact: "appointments@victorinsurance.com",       status: "tbd", notes: "" },
  { name: "Wellington",         contact: "appointments@wellingtonins.com",         status: "tbd", notes: "" },
  { name: "Propeller Bonds",    contact: "appointments@propellerbonds.com",        status: "tbd", notes: "" },
  { name: "XSB",                contact: "appointments@xsb.com",                  status: "tbd", notes: "" },
  { name: "Lamar General",      contact: "appointments@lamargeneralins.com",       status: "tbd", notes: "" },
  { name: "Kleeco",             contact: "appointments@kleeco.com",                status: "tbd", notes: "" },
  { name: "LEEO",               contact: "appointments@leeosafety.com",            status: "tbd", notes: "" },
  { name: "Rohrer and Associates", contact: "appointments@rohrerandassociates.com",status: "tbd", notes: "" },
  { name: "Nat Gen",            contact: "appointments@natgenins.com",             status: "tbd", notes: "" },
  { name: "AAA",                contact: "agentappointments@aaa.com",              status: "tbd", notes: "" },
  { name: "Embark",             contact: "agents@embarkgeneral.com",               status: "tbd", notes: "" },
  { name: "Liberty Surety",     contact: "appointments@libertymutual.com",         status: "tbd", notes: "" },
];
