/**
 * Carrier partners by solution line.
 * IMPORTANT: confirm current appointments before publishing — the brand guide prohibits
 * naming a carrier without current approval. Drop an SVG or PNG at /public/logos/<slug>.svg
 * (or .png) and set `logo` to show a logo instead of the typographic wordmark.
 */
export interface Carrier { slug: string; name: string; rating?: string; logo?: string }
export interface CarrierGroup { key: string; title: string; solution: string; carriers: Carrier[] }

/** Maps carrier slugs to their real logo image files in /public/logos/ */
const logoMap: Record<string, string> = {
  'aetna': '/logos/aetna.svg',
  'allianz': '/logos/allianz.png',
  'american-equity': '/logos/american-equity.png',
  'american-national': '/logos/american-national.png',
  'americo': '/logos/americo.png',
  'ameritas': '/logos/ameritas.png',
  'anthem': '/logos/anthem.svg',
  'aspida': '/logos/aspida.png',
  'assurity': '/logos/assurity.svg',
  'athene': '/logos/athene.svg',
  'augustar': '/logos/augustar.png',
  'banner': '/logos/banner.png',
  'bcbs': '/logos/bcbs.svg',
  'brighthouse': '/logos/brighthouse.svg',
  'centene': '/logos/centene.jpg',
  'cigna': '/logos/cigna.png',
  'colonial-penn': '/logos/colonial-penn.png',
  'corebridge': '/logos/corebridge.png',
  'delaware-life': '/logos/delaware-life.svg',
  'devoted': '/logos/devoted.svg',
  'equitable': '/logos/equitable.png',
  'equitrust': '/logos/equitrust.png',
  'fg': '/logos/fg.svg',
  'foresters': '/logos/foresters.svg',
  'global-atlantic': '/logos/global-atlantic.png',
  'globe-life': '/logos/globe-life.png',
  'guardian': '/logos/guardian.svg',
  'humana': '/logos/humana.png',
  'illinois-mutual': '/logos/illinois-mutual.png',
  'integrity': '/logos/integrity.png',
  'jackson': '/logos/jackson.svg',
  'john-hancock': '/logos/john-hancock.svg',
  'kaiser': '/logos/kaiser.png',
  'kansas-city-life': '/logos/kansas-city-life.png',
  'lafayette': '/logos/lafayette.svg',
  'lincoln': '/logos/lincoln.png',
  'massmutual': '/logos/massmutual.png',
  'medicare-supplement': '/logos/medicare-supplement.png',
  'midland-national': '/logos/midland-national.png',
  'molina': '/logos/molina.png',
  'mutual-of-omaha': '/logos/mutual-of-omaha.jpg',
  'nassau': '/logos/nassau.png',
  'national-guardian': '/logos/national-guardian.png',
  'nationwide': '/logos/nationwide.png',
  'north-american': '/logos/north-american.png',
  'oceanview': '/logos/oceanview.png',
  'oneamerica': '/logos/oneamerica.svg',
  'pacific-life': '/logos/pacific-life.svg',
  'penn-mutual': '/logos/penn-mutual.png',
  'petersen': '/logos/petersen.png',
  'principal': '/logos/principal.svg',
  'protective': '/logos/protective.svg',
  'prudential': '/logos/prudential.png',
  'sagicor': '/logos/sagicor.png',
  'securian': '/logos/securian.png',
  'security-benefit': '/logos/security-benefit.svg',
  'silver-sneakers': '/logos/silver-sneakers.png',
  'symetra': '/logos/symetra.png',
  'the-standard': '/logos/the-standard.png',
  'transamerica': '/logos/transamerica.png',
  'unitedhealthcare': '/logos/unitedhealthcare.png',
  'unum': '/logos/unum.png',
  'wellcare': '/logos/wellcare.png',
  'western-southern': '/logos/western-southern.svg',
}

const c = (slug: string, name: string, rating?: string): Carrier => ({ slug, name, rating, logo: logoMap[slug] })

export const carrierGroups: CarrierGroup[] = [
  { key: 'annuities', title: 'Annuities', solution: 'annuities', carriers: [
    c('allianz', 'Allianz Life', 'A+'),
    c('athene', 'Athene', 'A+'),
    c('nationwide', 'Nationwide', 'A+'),
    c('lincoln', 'Lincoln Financial', 'A'),
    c('north-american', 'North American', 'A+'),
    c('midland-national', 'Midland National', 'A+'),
    c('fg', 'F&G Annuities & Life', 'A'),
    c('american-equity', 'American Equity', 'A'),
    c('global-atlantic', 'Global Atlantic', 'A'),
    c('pacific-life', 'Pacific Life', 'A+'),
    c('corebridge', 'Corebridge Financial', 'A'),
    c('equitrust', 'EquiTrust Life', 'B++'),
    c('massmutual', 'MassMutual Ascend', 'A++'),
    c('symetra', 'Symetra', 'A'),
    c('oceanview', 'Oceanview Life', 'A-'),
    c('sagicor', 'Sagicor Life', 'A-'),
    c('jackson', 'Jackson National', 'A'),
    c('protective', 'Protective Life', 'A+'),
    c('security-benefit', 'Security Benefit', 'A-'),
    c('americo', 'Americo', 'A'),
    c('brighthouse', 'Brighthouse Financial', 'A'),
    c('equitable', 'Equitable Financial', 'A'),
    c('transamerica', 'Transamerica', 'A'),
    c('delaware-life', 'Delaware Life', 'A-'),
    c('nassau', 'Nassau Life', 'B++'),
    c('aspida', 'Aspida', 'A-'),
    c('western-southern', 'Western-Southern', 'A+'),
    c('lafayette', 'Lafayette Life', 'A+'),
    c('integrity', 'Integrity Life', 'A+'),
    c('augustar', 'AuguStar Financial', 'A'),
    c('prudential', 'Prudential', 'A+'),
  ]},
  { key: 'life', title: 'Life insurance', solution: 'life-insurance', carriers: [
    c('john-hancock', 'John Hancock', 'A+'),
    c('prudential', 'Prudential', 'A+'),
    c('lincoln', 'Lincoln Financial', 'A'),
    c('protective', 'Protective Life', 'A+'),
    c('transamerica', 'Transamerica', 'A'),
    c('mutual-of-omaha', 'Mutual of Omaha', 'A+'),
    c('pacific-life', 'Pacific Life', 'A+'),
    c('nationwide', 'Nationwide', 'A+'),
    c('securian', 'Securian Financial', 'A+'),
    c('penn-mutual', 'Penn Mutual', 'A+'),
    c('north-american', 'North American', 'A+'),
    c('foresters', 'Foresters Financial', 'A'),
    c('american-national', 'American National', 'A'),
    c('kansas-city-life', 'Kansas City Life', 'A-'),
    c('banner', 'Banner Life (Legal & General)', 'A'),
    c('corebridge', 'Corebridge Financial', 'A'),
    c('massmutual', 'MassMutual', 'A++'),
    c('guardian', 'Guardian', 'A++'),
    c('principal', 'Principal', 'A+'),
    c('allianz', 'Allianz Life', 'A+'),
    c('symetra', 'Symetra', 'A'),
    c('fg', 'F&G Annuities & Life', 'A'),
    c('american-equity', 'American Equity', 'A'),
    c('jackson', 'Jackson National', 'A'),
    c('equitable', 'Equitable Financial', 'A'),
    c('global-atlantic', 'Global Atlantic', 'A'),
    c('athene', 'Athene', 'A+'),
    c('midland-national', 'Midland National', 'A+'),
    c('brighthouse', 'Brighthouse Financial', 'A'),
    c('sagicor', 'Sagicor Life', 'A-'),
    c('americo', 'Americo', 'A'),
  ]},
  { key: 'care', title: 'Care planning', solution: 'care-planning', carriers: [
    c('mutual-of-omaha', 'Mutual of Omaha', 'A+'),
    c('nationwide', 'Nationwide', 'A+'),
    c('lincoln', 'Lincoln MoneyGuard', 'A'),
    c('oneamerica', 'OneAmerica', 'A+'),
    c('securian', 'Securian Financial', 'A+'),
    c('brighthouse', 'Brighthouse Financial', 'A'),
    c('national-guardian', 'National Guardian Life', 'A-'),
    c('equitrust', 'EquiTrust Life', 'B++'),
    c('pacific-life', 'Pacific Life', 'A+'),
    c('john-hancock', 'John Hancock', 'A+'),
    c('transamerica', 'Transamerica', 'A'),
    c('massmutual', 'MassMutual', 'A++'),
    c('protective', 'Protective Life', 'A+'),
    c('corebridge', 'Corebridge Financial', 'A'),
    c('global-atlantic', 'Global Atlantic', 'A'),
  ]},
  { key: 'medicare', title: 'Medicare planning', solution: 'medicare-planning', carriers: [
    c('aetna', 'Aetna', 'A'),
    c('humana', 'Humana', 'A-'),
    c('unitedhealthcare', 'UnitedHealthcare', 'A+'),
    c('cigna', 'Cigna Healthcare', 'A'),
    c('anthem', 'Anthem BCBS', 'A'),
    c('mutual-of-omaha', 'Mutual of Omaha', 'A+'),
    c('wellcare', 'Wellcare', 'A-'),
    c('devoted', 'Devoted Health'),
    c('centene', 'Centene', 'A-'),
    c('molina', 'Molina Healthcare', 'A-'),
    c('kaiser', 'Kaiser Permanente', 'A+'),
    c('bcbs', 'Blue Cross Blue Shield', 'A'),
    c('medicare-supplement', 'State Farm', 'A++'),
    c('colonial-penn', 'Colonial Penn', 'A+'),
    c('globe-life', 'Globe Life', 'A'),
    c('silver-sneakers', 'Bankers Life', 'A+'),
  ]},
  { key: 'disability', title: 'Disability income', solution: 'disability-income', carriers: [
    c('guardian', 'Guardian', 'A++'),
    c('principal', 'Principal', 'A+'),
    c('massmutual', 'MassMutual', 'A++'),
    c('ameritas', 'Ameritas', 'A'),
    c('illinois-mutual', 'Illinois Mutual', 'A-'),
    c('assurity', 'Assurity', 'A-'),
    c('the-standard', 'The Standard', 'A'),
    c('petersen', 'Petersen International'),
    c('mutual-of-omaha', 'Mutual of Omaha', 'A+'),
    c('lincoln', 'Lincoln Financial', 'A'),
    c('prudential', 'Prudential', 'A+'),
    c('protective', 'Protective Life', 'A+'),
    c('nationwide', 'Nationwide', 'A+'),
    c('securian', 'Securian Financial', 'A+'),
    c('transamerica', 'Transamerica', 'A'),
    c('unum', 'Unum', 'A-'),
  ]},
]

export const allCarriers: Carrier[] = Array.from(new Map(carrierGroups.flatMap((g) => g.carriers).map((x) => [x.slug, x])).values())

export const stateNames: Record<string, string> = {
  AL:'Alabama', AK:'Alaska', AZ:'Arizona', AR:'Arkansas', CA:'California', CO:'Colorado', CT:'Connecticut', DE:'Delaware', FL:'Florida', GA:'Georgia',
  HI:'Hawaii', ID:'Idaho', IL:'Illinois', IN:'Indiana', IA:'Iowa', KS:'Kansas', KY:'Kentucky', LA:'Louisiana', ME:'Maine', MD:'Maryland',
  MA:'Massachusetts', MI:'Michigan', MN:'Minnesota', MS:'Mississippi', MO:'Missouri', MT:'Montana', NE:'Nebraska', NV:'Nevada', NH:'New Hampshire', NJ:'New Jersey',
  NM:'New Mexico', NY:'New York', NC:'North Carolina', ND:'North Dakota', OH:'Ohio', OK:'Oklahoma', OR:'Oregon', PA:'Pennsylvania', RI:'Rhode Island', SC:'South Carolina',
  SD:'South Dakota', TN:'Tennessee', TX:'Texas', UT:'Utah', VT:'Vermont', VA:'Virginia', WA:'Washington', WV:'West Virginia', WI:'Wisconsin', WY:'Wyoming',
}
